<a href="https://colab.research.google.com/github/ROHINI-H/websites/blob/master/data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

data preprocessing

Importing the libraries

In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


importing the dataset

In [13]:
data=pd.read_csv("Data preprocessing.csv")
X=data.iloc[:,1:4].values
y=data.iloc[:,-1].values

In [14]:
print(y)

['yes' 'no' 'no' 'no' 'yes' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'no'
 'yes' 'yes' 'no' 'yes']


finding the missing data

In [15]:
from sklearn.impute import SimpleImputer
imputer=SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])


In [16]:
print(X)

[['India' 26.0 65000.0]
 ['USA' 32.0 70000.0]
 ['China' 56.0 62000.0]
 ['USA' 48.0 72000.0]
 ['Australia' 33.0 50000.0]
 ['Australia' 59.0 56000.0]
 ['India' 18.0 68000.0]
 ['USA' 29.0 73000.0]
 ['India' 37.46666666666667 68000.0]
 ['Australia' 36.0 52000.0]
 ['India' 29.0 64000.0]
 ['France' 42.0 30000.0]
 ['USA' 28.0 76000.0]
 ['USA' 37.46666666666667 74000.0]
 ['China' 33.0 60000.0]
 ['China' 35.0 61000.0]
 ['Australia' 58.0 55000.0]]


encoding the categorical data

In [17]:
from sklearn.preprocessing import LabelEncoder
i=LabelEncoder()
X[:,0]=i.fit_transform(X[:,0])

In [18]:
print(X)

[[3 26.0 65000.0]
 [4 32.0 70000.0]
 [1 56.0 62000.0]
 [4 48.0 72000.0]
 [0 33.0 50000.0]
 [0 59.0 56000.0]
 [3 18.0 68000.0]
 [4 29.0 73000.0]
 [3 37.46666666666667 68000.0]
 [0 36.0 52000.0]
 [3 29.0 64000.0]
 [2 42.0 30000.0]
 [4 28.0 76000.0]
 [4 37.46666666666667 74000.0]
 [1 33.0 60000.0]
 [1 35.0 61000.0]
 [0 58.0 55000.0]]


splitting data into train/test set

In [19]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [20]:
print(X_train)

[[4 37.46666666666667 74000.0]
 [0 33.0 50000.0]
 [1 56.0 62000.0]
 [1 33.0 60000.0]
 [3 29.0 64000.0]
 [4 29.0 73000.0]
 [0 58.0 55000.0]
 [2 42.0 30000.0]
 [4 48.0 72000.0]
 [3 26.0 65000.0]
 [0 59.0 56000.0]
 [1 35.0 61000.0]
 [4 28.0 76000.0]]


In [21]:
print(X_test)

[[4 32.0 70000.0]
 [3 18.0 68000.0]
 [3 37.46666666666667 68000.0]
 [0 36.0 52000.0]]


In [22]:
print(y_train)

['yes' 'yes' 'no' 'yes' 'yes' 'yes' 'yes' 'no' 'no' 'yes' 'no' 'no' 'no']


In [23]:
print(y_test)

['no' 'yes' 'yes' 'no']


feature scaling

In [24]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()
X_train=ss.fit_transform(X_train)
X_test=ss.fit_transform(X_test)

In [25]:
print(X_train)

[[ 1.20842061 -0.17669738  1.06412772]
 [-1.30509426 -0.56534238 -0.96031038]
 [-0.67671554  1.43588932  0.05190867]
 [-0.67671554 -0.56534238 -0.11679451]
 [ 0.58004189 -0.91338267  0.22061184]
 [ 1.20842061 -0.91338267  0.97977613]
 [-1.30509426  1.60990947 -0.53855244]
 [-0.04833682  0.21774829 -2.64734213]
 [ 1.20842061  0.73980873  0.89542454]
 [ 0.58004189 -1.17441289  0.30496343]
 [-1.30509426  1.69691954 -0.45420086]
 [-0.67671554 -0.39132223 -0.03244292]
 [ 1.20842061 -1.00039275  1.23283089]]


In [26]:
print(X_test)

[[ 1.          0.14731458  0.75727123]
 [ 0.33333333 -1.67245372  0.48189987]
 [ 0.33333333  0.85789077  0.48189987]
 [-1.66666667  0.66724838 -1.72107098]]
